"""Create tables

Revision ID: 7487fc4705e5
Revises: 
Create Date: 2023-10-04 19:45:48.055846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7487fc4705e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('User_ID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('restaurants',
    sa.Column('Restaurant_ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Location', sa.String(), nullable=True),
    sa.Column('Amenities', sa.String(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Owner_User_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Owner_User_ID'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('Restaurant_ID'),
    sa.UniqueConstraint('Owner_User_ID')
    )
    op.create_table('reviews',
    sa.Column('Review_ID', sa.Integer(), nullable=False),
    sa.Column('Rating', sa.Float(precision=5, asdecimal=2), nullable=True),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('Date_Created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('User_ID', sa.Integer(), nullable=True),
    sa.Column('Restaurant_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Restaurant_ID'], ['restaurants.Restaurant_ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('Review_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('restaurants')
    op.drop_table('users')
    # ### end Alembic commands ###

