"""empty message

Revision ID: d7481a13ce92
Revises: 88313479cf30
Create Date: 2023-10-03 21:03:12.539887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7481a13ce92'
down_revision = '88313479cf30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('MenuItem_ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Price', sa.Float(precision=2), nullable=True),
    sa.Column('Image_URL', sa.String(), nullable=True),
    sa.Column('Restaurant_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Restaurant_ID'], ['restaurants.Restaurant_ID'], ),
    sa.PrimaryKeyConstraint('MenuItem_ID')
    )
    op.create_table('reviews',
    sa.Column('Review_ID', sa.Integer(), nullable=False),
    sa.Column('Rating', sa.Float(precision=5, asdecimal=2), nullable=True),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('Date_Created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('User_ID', sa.Integer(), nullable=True),
    sa.Column('Restaurant_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Restaurant_ID'], ['restaurants.Restaurant_ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('Review_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('menu_items')
    # ### end Alembic commands ###
